name: 'quant_pipeline'
version: '1.0.0'
config-version: 2

profile: 'quant_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  quant_pipeline:
    features:
      +materialized: table
    fct_4h_features_tbm:
      +materialized: table
